@file:Suppress("unused")

object Versions {
    const val kotlin = "1.6.10"
    const val kotlinSerialization = "1.3.0"
    const val coroutines = "1.6.0"
    const val lifecycle = "2.2.0"
    const val datastorePreferences = "1.0.0"
    const val accompanistPermissions = "0.20.0"
    const val gradle = "7.1.2"
    const val gradlePlugin = "1.6.10"
    const val appcompat = "1.4.0"
    const val material = "1.5.0"
    const val javaxInject = "1"
    const val dagger = "2.40.2"
    const val timber = "5.0.1"
    const val startup = "1.0.0"
    const val room = "2.4.2"
    const val retrofit2 = "2.9.0"
    const val serializationConverter = "0.8.0"
    const val interceptor = "4.10.0"
    const val compose = "1.2.0-alpha04"
    const val composeActivity = "1.4.0"
    const val accompanist = "0.19.0"
    const val navigation = "2.4.1"
    const val hiltNavigation = "1.0.0"
    const val lifecycleViewModel = "2.4.0"
    const val foundation = "1.1.1"
    const val constraintCompose = "1.0.0"
    const val kotlinxDatetime = "0.3.1"
    const val okHttp = "4.10.0"

    // test
    const val junit = "4.13.2"
    const val mockk = "1.12.1"
    const val core = "2.1.0"
    const val robolectric = "4.7.3"
    const val coreTest = "1.3.0"
}
